version: '3.7'

services:
  dnevnik365:
    build: .
    volumes:
      - ./dnevnik365/:/app/
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL='postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}'
    depends_on:
      - db
      - nginx
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
  redis:
    image: redis:7.2.4
