version: '3.7'

services:
  dnevnik365:
    build: .
    volumes:
      - ./dnevnik365/:/app/
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL='postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}'
    depends_on:
      - users_db
      - purposes_db
      - nginx
  users_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
  purposes_db:
    image: redis:7.2.4
    environment:
      - REDIS_HOST=${HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6378:6378
  homework_db:
    image: redis:7.2.4
    environment:
      - REDIS_HOST=${HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6380:6380
