name: check
on: [pull_request, release]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: make test
      - name: test-cov
        run: make test-cov
